// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMessagePB.proto

package com.hzins.netty.protocol;

public final class PushMessageProtoc {
  private PushMessageProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PushMessagePBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PushMessagePB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 fromUserId = 5;</code>
     *
     * <pre>
     *发件人
     * </pre>
     */
    boolean hasFromUserId();
    /**
     * <code>optional int64 fromUserId = 5;</code>
     *
     * <pre>
     *发件人
     * </pre>
     */
    long getFromUserId();

    /**
     * <code>optional int64 toUserId = 6;</code>
     *
     * <pre>
     *收件人
     * </pre>
     */
    boolean hasToUserId();
    /**
     * <code>optional int64 toUserId = 6;</code>
     *
     * <pre>
     *收件人
     * </pre>
     */
    long getToUserId();

    /**
     * <code>optional bytes parameters = 7;</code>
     */
    boolean hasParameters();
    /**
     * <code>optional bytes parameters = 7;</code>
     */
    com.google.protobuf.ByteString getParameters();

    /**
     * <code>optional string cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>optional string cmd = 1;</code>
     */
    java.lang.String getCmd();
    /**
     * <code>optional string cmd = 1;</code>
     */
    com.google.protobuf.ByteString
        getCmdBytes();
  }
  /**
   * Protobuf type {@code PushMessagePB}
   */
  public static final class PushMessagePB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PushMessagePB)
      PushMessagePBOrBuilder {
    // Use PushMessagePB.newBuilder() to construct.
    private PushMessagePB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushMessagePB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushMessagePB defaultInstance;
    public static PushMessagePB getDefaultInstance() {
      return defaultInstance;
    }

    public PushMessagePB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushMessagePB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cmd_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000001;
              fromUserId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000002;
              toUserId_ = input.readInt64();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000004;
              parameters_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.class, com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Builder.class);
    }

    public static com.google.protobuf.Parser<PushMessagePB> PARSER =
        new com.google.protobuf.AbstractParser<PushMessagePB>() {
      public PushMessagePB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushMessagePB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushMessagePB> getParserForType() {
      return PARSER;
    }

    public interface PushOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PushMessagePB.Push)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 pushid = 1;</code>
       */
      boolean hasPushid();
      /**
       * <code>optional int32 pushid = 1;</code>
       */
      int getPushid();

      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      boolean hasContent();
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      java.lang.String getContent();
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      com.google.protobuf.ByteString
          getContentBytes();

      /**
       * <code>optional int32 badge = 4;</code>
       *
       * <pre>
       *图标数字，未读数
       * </pre>
       */
      boolean hasBadge();
      /**
       * <code>optional int32 badge = 4;</code>
       *
       * <pre>
       *图标数字，未读数
       * </pre>
       */
      int getBadge();

      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      boolean hasSound();
      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      java.lang.String getSound();
      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      com.google.protobuf.ByteString
          getSoundBytes();
    }
    /**
     * Protobuf type {@code PushMessagePB.Push}
     *
     * <pre>
     *推送基本信息，该推送包含了多个值
     * </pre>
     */
    public static final class Push extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:PushMessagePB.Push)
        PushOrBuilder {
      // Use Push.newBuilder() to construct.
      private Push(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Push(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Push defaultInstance;
      public static Push getDefaultInstance() {
        return defaultInstance;
      }

      public Push getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Push(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                pushid_ = input.readInt32();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                content_ = bs;
                break;
              }
              case 32: {
                bitField0_ |= 0x00000004;
                badge_ = input.readInt32();
                break;
              }
              case 42: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                sound_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_Push_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_Push_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.class, com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.Builder.class);
      }

      public static com.google.protobuf.Parser<Push> PARSER =
          new com.google.protobuf.AbstractParser<Push>() {
        public Push parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Push(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Push> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int PUSHID_FIELD_NUMBER = 1;
      private int pushid_;
      /**
       * <code>optional int32 pushid = 1;</code>
       */
      public boolean hasPushid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 pushid = 1;</code>
       */
      public int getPushid() {
        return pushid_;
      }

      public static final int CONTENT_FIELD_NUMBER = 2;
      private java.lang.Object content_;
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string content = 2;</code>
       *
       * <pre>
       *推送内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BADGE_FIELD_NUMBER = 4;
      private int badge_;
      /**
       * <code>optional int32 badge = 4;</code>
       *
       * <pre>
       *图标数字，未读数
       * </pre>
       */
      public boolean hasBadge() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 badge = 4;</code>
       *
       * <pre>
       *图标数字，未读数
       * </pre>
       */
      public int getBadge() {
        return badge_;
      }

      public static final int SOUND_FIELD_NUMBER = 5;
      private java.lang.Object sound_;
      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      public boolean hasSound() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      public java.lang.String getSound() {
        java.lang.Object ref = sound_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sound_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string sound = 5;</code>
       *
       * <pre>
       * 语音
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSoundBytes() {
        java.lang.Object ref = sound_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sound_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        pushid_ = 0;
        content_ = "";
        badge_ = 0;
        sound_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, pushid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getContentBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(4, badge_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(5, getSoundBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, pushid_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getContentBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, badge_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, getSoundBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PushMessagePB.Push}
       *
       * <pre>
       *推送基本信息，该推送包含了多个值
       * </pre>
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PushMessagePB.Push)
          com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.PushOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_Push_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_Push_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.class, com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.Builder.class);
        }

        // Construct using com.hzins.pb.protocol.PushMessageProtoc.PushMessagePB.Push.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          pushid_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          content_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          badge_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          sound_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_Push_descriptor;
        }

        public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push getDefaultInstanceForType() {
          return com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.getDefaultInstance();
        }

        public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push build() {
          com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push buildPartial() {
          com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push result = new com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.pushid_ = pushid_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.content_ = content_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.badge_ = badge_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.sound_ = sound_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push) {
            return mergeFrom((com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push other) {
          if (other == com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push.getDefaultInstance()) return this;
          if (other.hasPushid()) {
            setPushid(other.getPushid());
          }
          if (other.hasContent()) {
            bitField0_ |= 0x00000002;
            content_ = other.content_;
            onChanged();
          }
          if (other.hasBadge()) {
            setBadge(other.getBadge());
          }
          if (other.hasSound()) {
            bitField0_ |= 0x00000008;
            sound_ = other.sound_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Push) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int pushid_ ;
        /**
         * <code>optional int32 pushid = 1;</code>
         */
        public boolean hasPushid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 pushid = 1;</code>
         */
        public int getPushid() {
          return pushid_;
        }
        /**
         * <code>optional int32 pushid = 1;</code>
         */
        public Builder setPushid(int value) {
          bitField0_ |= 0x00000001;
          pushid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 pushid = 1;</code>
         */
        public Builder clearPushid() {
          bitField0_ = (bitField0_ & ~0x00000001);
          pushid_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object content_ = "";
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public boolean hasContent() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public java.lang.String getContent() {
          java.lang.Object ref = content_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              content_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public com.google.protobuf.ByteString
            getContentBytes() {
          java.lang.Object ref = content_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            content_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public Builder setContent(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          content_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        /**
         * <code>optional string content = 2;</code>
         *
         * <pre>
         *推送内容
         * </pre>
         */
        public Builder setContentBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          content_ = value;
          onChanged();
          return this;
        }

        private int badge_ ;
        /**
         * <code>optional int32 badge = 4;</code>
         *
         * <pre>
         *图标数字，未读数
         * </pre>
         */
        public boolean hasBadge() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 badge = 4;</code>
         *
         * <pre>
         *图标数字，未读数
         * </pre>
         */
        public int getBadge() {
          return badge_;
        }
        /**
         * <code>optional int32 badge = 4;</code>
         *
         * <pre>
         *图标数字，未读数
         * </pre>
         */
        public Builder setBadge(int value) {
          bitField0_ |= 0x00000004;
          badge_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 badge = 4;</code>
         *
         * <pre>
         *图标数字，未读数
         * </pre>
         */
        public Builder clearBadge() {
          bitField0_ = (bitField0_ & ~0x00000004);
          badge_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object sound_ = "";
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public boolean hasSound() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public java.lang.String getSound() {
          java.lang.Object ref = sound_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              sound_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public com.google.protobuf.ByteString
            getSoundBytes() {
          java.lang.Object ref = sound_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sound_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public Builder setSound(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          sound_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public Builder clearSound() {
          bitField0_ = (bitField0_ & ~0x00000008);
          sound_ = getDefaultInstance().getSound();
          onChanged();
          return this;
        }
        /**
         * <code>optional string sound = 5;</code>
         *
         * <pre>
         * 语音
         * </pre>
         */
        public Builder setSoundBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          sound_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:PushMessagePB.Push)
      }

      static {
        defaultInstance = new Push(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:PushMessagePB.Push)
    }

    private int bitField0_;
    public static final int FROMUSERID_FIELD_NUMBER = 5;
    private long fromUserId_;
    /**
     * <code>optional int64 fromUserId = 5;</code>
     *
     * <pre>
     *发件人
     * </pre>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 fromUserId = 5;</code>
     *
     * <pre>
     *发件人
     * </pre>
     */
    public long getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 6;
    private long toUserId_;
    /**
     * <code>optional int64 toUserId = 6;</code>
     *
     * <pre>
     *收件人
     * </pre>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 toUserId = 6;</code>
     *
     * <pre>
     *收件人
     * </pre>
     */
    public long getToUserId() {
      return toUserId_;
    }

    public static final int PARAMETERS_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString parameters_;
    /**
     * <code>optional bytes parameters = 7;</code>
     */
    public boolean hasParameters() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes parameters = 7;</code>
     */
    public com.google.protobuf.ByteString getParameters() {
      return parameters_;
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private java.lang.Object cmd_;
    /**
     * <code>optional string cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string cmd = 1;</code>
     */
    public java.lang.String getCmd() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmd_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cmd = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmdBytes() {
      java.lang.Object ref = cmd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      fromUserId_ = 0L;
      toUserId_ = 0L;
      parameters_ = com.google.protobuf.ByteString.EMPTY;
      cmd_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(5, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(6, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(7, parameters_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCmdBytes());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, fromUserId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, toUserId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, parameters_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PushMessagePB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PushMessagePB)
        com.hzins.netty.protocol.PushMessageProtoc.PushMessagePBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.class, com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.Builder.class);
      }

      // Construct using com.hzins.pb.protocol.PushMessageProtoc.PushMessagePB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fromUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        parameters_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        cmd_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hzins.netty.protocol.PushMessageProtoc.internal_static_PushMessagePB_descriptor;
      }

      public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB getDefaultInstanceForType() {
        return com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.getDefaultInstance();
      }

      public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB build() {
        com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB buildPartial() {
        com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB result = new com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.parameters_ = parameters_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB) {
          return mergeFrom((com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB other) {
        if (other == com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB.getDefaultInstance()) return this;
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasParameters()) {
          setParameters(other.getParameters());
        }
        if (other.hasCmd()) {
          bitField0_ |= 0x00000008;
          cmd_ = other.cmd_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hzins.netty.protocol.PushMessageProtoc.PushMessagePB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long fromUserId_ ;
      /**
       * <code>optional int64 fromUserId = 5;</code>
       *
       * <pre>
       *发件人
       * </pre>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 fromUserId = 5;</code>
       *
       * <pre>
       *发件人
       * </pre>
       */
      public long getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>optional int64 fromUserId = 5;</code>
       *
       * <pre>
       *发件人
       * </pre>
       */
      public Builder setFromUserId(long value) {
        bitField0_ |= 0x00000001;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 fromUserId = 5;</code>
       *
       * <pre>
       *发件人
       * </pre>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fromUserId_ = 0L;
        onChanged();
        return this;
      }

      private long toUserId_ ;
      /**
       * <code>optional int64 toUserId = 6;</code>
       *
       * <pre>
       *收件人
       * </pre>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 toUserId = 6;</code>
       *
       * <pre>
       *收件人
       * </pre>
       */
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>optional int64 toUserId = 6;</code>
       *
       * <pre>
       *收件人
       * </pre>
       */
      public Builder setToUserId(long value) {
        bitField0_ |= 0x00000002;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 toUserId = 6;</code>
       *
       * <pre>
       *收件人
       * </pre>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString parameters_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes parameters = 7;</code>
       */
      public boolean hasParameters() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes parameters = 7;</code>
       */
      public com.google.protobuf.ByteString getParameters() {
        return parameters_;
      }
      /**
       * <code>optional bytes parameters = 7;</code>
       */
      public Builder setParameters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        parameters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes parameters = 7;</code>
       */
      public Builder clearParameters() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parameters_ = getDefaultInstance().getParameters();
        onChanged();
        return this;
      }

      private java.lang.Object cmd_ = "";
      /**
       * <code>optional string cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string cmd = 1;</code>
       */
      public java.lang.String getCmd() {
        java.lang.Object ref = cmd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cmd_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cmd = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        java.lang.Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cmd = 1;</code>
       */
      public Builder setCmd(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cmd_ = getDefaultInstance().getCmd();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmd = 1;</code>
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cmd_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PushMessagePB)
    }

    static {
      defaultInstance = new PushMessagePB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PushMessagePB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessagePB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushMessagePB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushMessagePB_Push_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PushMessagePB_Push_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PushMessagePB.proto\"\235\001\n\rPushMessagePB\022" +
      "\022\n\nfromUserId\030\005 \001(\003\022\020\n\010toUserId\030\006 \001(\003\022\022\n" +
      "\nparameters\030\007 \001(\014\022\013\n\003cmd\030\001 \001(\t\032E\n\004Push\022\016" +
      "\n\006pushid\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\022\r\n\005badge" +
      "\030\004 \001(\005\022\r\n\005sound\030\005 \001(\tB*\n\025com.hzins.pb.pr" +
      "otocolB\021PushMessageProtoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PushMessagePB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PushMessagePB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PushMessagePB_descriptor,
        new java.lang.String[] { "FromUserId", "ToUserId", "Parameters", "Cmd", });
    internal_static_PushMessagePB_Push_descriptor =
      internal_static_PushMessagePB_descriptor.getNestedTypes().get(0);
    internal_static_PushMessagePB_Push_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PushMessagePB_Push_descriptor,
        new java.lang.String[] { "Pushid", "Content", "Badge", "Sound", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
